language: c
compiler: clang

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
      cache:
        apt: true
        ccache: true
      script: cmake . && make && make test

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install openssl@1.1 ccache && export PATH=\"/usr/local/opt/ccache/libexec:$PATH\""
      cache:
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
      script: cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 . && make && make test


before_install:
    - eval "${MATRIX_EVAL}"
